<img src="http://sct.inf.utfsm.cl/wp-content/uploads/2020/04/logo_di.png" style="width:60%">

<center>
    <h1> ILI285/INF285 Computación Científica </h1>
    <h1> Numpy </h1>
</center>

## ¿Qué es Numpy?

[Numpy](https://numpy.org) es una librería para computación científica en Python. Esta provee arreglos multidimensionales que son utilizados para representar, por ejemplo, vectores y matrices. Adicionalmente la librería tiene una gran cantidad de rutinas optimizadas para trabajar con este tipo de arreglos, tales como rutinas de algebra lineal, estadística, ordenamiento, transformaciones de Fourier, entre otros.

Hoy en día varias librerias famosas utilizan numpy, algunas de estas son:

* [Pandas](https://pandas.pydata.org)
* [Matplotlib](https://matplotlib.org)
* [Scikit‑learn](https://scikit-learn.org)
* [Keras](https://keras.io)

In [1]:
import numpy as np

# Arreglos

Para comenzar a utilizar Numpy es necesario conocer la estructura de datos que este provee (arrays). En esta sección mostraremos como representar vectores y matrices además de mostrar algunas operaciones de utilidad.

## Vectores

$$
 \vec{x} = \begin{bmatrix}
     u_{1} \\
     u_{2} \\ 
     \vdots \\
     u_{n} \\
 \end{bmatrix}
$$

Para generar un vector utilizamos la siguiente línea de código:

In [63]:
x = np.array( [1., 2., 9., 3., .2] ) # Se usa el . para que se inicialice con tipo float

In [64]:
print(x)

[1.  2.  9.  3.  0.2]


Podemos verificar la dimensión de un vector utilizando:

In [62]:
x.shape

(5,)

Numpy se encarga de manejar la dimensión de los vectores al momento de operarlos. Si usted desea trabajar con vectores filas o columnas puede hacer lo siguiente:

In [4]:
temporal = x.reshape(5,1)
print(temporal)
print("Dim:", temporal.shape)

[[1. ]
 [2. ]
 [9. ]
 [3. ]
 [0.2]]
Dim: (5, 1)


In [5]:
temporal = x.reshape(1,5)
print(temporal)
print("Dim:", temporal.shape)

[[1.  2.  9.  3.  0.2]]
Dim: (1, 5)


In [6]:
x.dtype

dtype('float64')

## Funciones que generan vectores

**Vector de 1's**

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**Vector de 0's**

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## Sistema de indice 

In [9]:
x[-1]

0.2

In [10]:
x[:]

array([1. , 2. , 9. , 3. , 0.2])

In [11]:
x[2:]

array([9. , 3. , 0.2])

## Matrices

$$
    A = \begin{bmatrix}
        a_{11}&a_{12}&\cdots &a_{1n} \\
        a_{21}&a_{22}&\cdots &a_{2n} \\
        \vdots &\vdots &\ddots &\vdots \\
        a_{m1}&a_{m2}&\cdots &a_{mn}
     \end{bmatrix}
$$

Para poder generar una matriz utilizamos:

In [56]:
A = np.array([
    [5., 2., 3., 4., 7], # fila
    [1., 3., 2., 2., 0], # fila
    [0., 2., 5., 1., 2],
    [2., 4., 4., 4., 0],
    [3., 1.2, 7., 4., 9]
])

In [57]:
A

array([[5. , 2. , 3. , 4. , 7. ],
       [1. , 3. , 2. , 2. , 0. ],
       [0. , 2. , 5. , 1. , 2. ],
       [2. , 4. , 4. , 4. , 0. ],
       [3. , 1.2, 7. , 4. , 9. ]])

Al igual que los vectores, podemos conocer la dimensión de la matriz $A$ utilizando:

In [14]:
A.shape

(5, 5)

## Funciones que generan matrices

**Matriz de 1's**

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Matriz de 0's**

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Matriz con una diagonal**

In [17]:
np.diag(np.array([1.,2.,3.,4.,5.]))

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

**Matriz identidad**

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Sistema de indices

In [19]:
A[:,:]

array([[5. , 2. , 3. , 4. , 7. ],
       [1. , 3. , 2. , 2. , 0. ],
       [0. , 2. , 5. , 1. , 2. ],
       [2. , 4. , 4. , 4. , 0. ],
       [3. , 1.2, 7. , 4. , 9. ]])

In [20]:
i = 2 # fila
A[i]

array([0., 2., 5., 1., 2.])

In [21]:
j = 3 # columna
A[:, j] 

array([4., 2., 1., 4., 4.])

In [22]:
A[i, j]

1.0

## Operaciones básicas

Las operaciones aritméticas las realiza elemento a elemento o *element-wise*

In [23]:
x

array([1. , 2. , 9. , 3. , 0.2])

**Suma**:

In [24]:
x + x

array([ 2. ,  4. , 18. ,  6. ,  0.4])

**Resta**:

In [25]:
x-x

array([0., 0., 0., 0., 0.])

**Multiplicación**:

In [26]:
3 * x

array([ 3. ,  6. , 27. ,  9. ,  0.6])

**División**:

In [27]:
x/2

array([0.5, 1. , 4.5, 1.5, 0.1])

**Potencia**:

In [28]:
x ** 2

array([1.0e+00, 4.0e+00, 8.1e+01, 9.0e+00, 4.0e-02])

In [29]:
b = x + 2 * x

In [30]:
b

array([ 3. ,  6. , 27. ,  9. ,  0.6])

### Producto punto, Producto Matriz-Vector, Producto Matriz-Matriz

In [31]:
np.dot(np.array([1, 0]), np.array([0, 1]))

0

In [32]:
np.dot(A, x)

array([49.4, 31. , 52.4, 58. , 82.2])

In [33]:
np.dot(A, 2 * A.T)

array([[206.  ,  50.  ,  74.  ,  92.  , 234.8 ],
       [ 50.  ,  36.  ,  36.  ,  60.  ,  57.2 ],
       [ 74.  ,  36.  ,  68.  ,  64.  , 118.8 ],
       [ 92.  ,  60.  ,  64.  , 104.  , 109.6 ],
       [234.8 ,  57.2 , 118.8 , 109.6 , 312.88]])

### Norma

In [48]:
v = 1 /  2 * np.array([np.sqrt(2), np.sqrt(2)])
print("Norma Euclidiana: ", np.linalg.norm(v, ord=2))

Norma Euclidiana:  1.0


In [52]:
np.sqrt(np.sum(v ** 2)) # Aplicar la definicion

1.0

## Operaciones sobre matrices

### Transpuesta

In [38]:
A.T, np.transpose(A)

(array([[5. , 1. , 0. , 2. , 3. ],
        [2. , 3. , 2. , 4. , 1.2],
        [3. , 2. , 5. , 4. , 7. ],
        [4. , 2. , 1. , 4. , 4. ],
        [7. , 0. , 2. , 0. , 9. ]]),
 array([[5. , 1. , 0. , 2. , 3. ],
        [2. , 3. , 2. , 4. , 1.2],
        [3. , 2. , 5. , 4. , 7. ],
        [4. , 2. , 1. , 4. , 4. ],
        [7. , 0. , 2. , 0. , 9. ]]))

### Inversa

Podemos calcular la inversa de una matriz utilizando:

In [39]:
A_1 = np.linalg.inv(A)

In [40]:
I = np.dot(A,A_1)
print(I)

[[ 1.00000000e+00  0.00000000e+00 -5.55111512e-16 -1.66533454e-16
  -5.55111512e-17]
 [-1.11022302e-16  1.00000000e+00 -2.22044605e-16  5.55111512e-17
   0.00000000e+00]
 [-8.32667268e-17  0.00000000e+00  1.00000000e+00  3.33066907e-16
  -2.22044605e-16]
 [-2.22044605e-16  2.22044605e-16 -4.44089210e-16  1.00000000e+00
   0.00000000e+00]
 [-3.74700271e-16  8.88178420e-16 -3.33066907e-16  1.66533454e-16
   1.00000000e+00]]


Si verificamos la diagonal nos daremos cuenta que son solo 1's. Los demás números de la matriz son números muy cercanos a 0, por lo que podemos decir que obtuvimos la matriz identidad.

In [58]:
np.diag(I)

array([1., 1., 1., 1., 1.])

# OJO

Si usted necesita resolver:

$$
\vec{x} = A^{-1} \vec{b}
$$

No calcule la inversa! Mejor resuelva el sistema de ecuaciones:

$$
A\vec{x} = \vec{b}
$$

Es mas eficiente. Para realizar esto podemos hacer lo siguiente:

In [42]:
A = np.array([
    [5., 2., 3., 4., 7], # fila
    [1., 3., 2., 2., 0], # fila
    [0., 2., 5., 1., 2],
    [2., 4., 4., 4., 0],
    [3., 1.2, 7., 4., 9]
])

b = [7,5,3,2,1]

In [43]:
np.linalg.solve(A,b)

array([ 0.86666667,  4.        , -0.94222222, -2.99111111,  1.35111111])

Que es lo mismo que haber hecho:

In [44]:
A_1 = np.linalg.inv(A)
np.dot(A_1,b)

array([ 0.86666667,  4.        , -0.94222222, -2.99111111,  1.35111111])

# Ejemplos utiles

¿ Como accedemos a cada fila de una matriz utilizando un loop? 

In [45]:
A = np.array([
    [5., 2., 3., 4., 7], # fila
    [1., 3., 2., 2., 0], # fila
    [0., 2., 5., 1., 2],
    [2., 4., 4., 4., 0],
    [3., 1.2, 7., 4., 9]
])

In [46]:
for i in range(0,A.shape[0]):
    print(A[i,:])

[5. 2. 3. 4. 7.]
[1. 3. 2. 2. 0.]
[0. 2. 5. 1. 2.]
[2. 4. 4. 4. 0.]
[3.  1.2 7.  4.  9. ]


¿Y a cada columna?

In [47]:
for k in range(0,A.shape[1]):
    print(A[:,k])

[5. 1. 0. 2. 3.]
[2.  3.  2.  4.  1.2]
[3. 2. 5. 4. 7.]
[4. 2. 1. 4. 4.]
[7. 0. 2. 0. 9.]
